# Server settings (ServerProperties)
server:
  port: 9090
  contextPath: /
  # Tomcat specifics
  tomcat:
    # 打开Tomcat的Access日志，并可以设置日志格式的方法
    # accessLogEnabled: false
    basedir:
    backgroundProcessorDelay: 30
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
  session:
    timeout: 30 # secs


# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  mvc:
    static-path-pattern: "/static/**"
  profiles:
    active: dev